# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="mhalder"
VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python

# set env for zle
export EDITOR=vim
export VISUAL='vim -f'

# set locale to english because of git
export LC_ALL=en_US.UTF-8

# switch of annoying beep
setopt nobeep

# take extension and completion to its limit
setopt extendedglob

# fix 'git diff HEAD^' without escaping
unsetopt nomatch

# and a bunch of other stuff
setopt alwayslastprompt
setopt no_alwaystoend
setopt autolist
setopt automenu
setopt autonamedirs
setopt autoparamkeys
setopt autoparamslash
setopt autoremoveslash
setopt no_bashautolist
setopt completealiases
setopt completeinword
setopt hashlistall
setopt no_listambiguous
setopt no_listbeep
setopt listpacked
setopt listrowsfirst
setopt listtypes
setopt no_menucomplete
setopt no_recexact

# use vv instead of esc in vi-mode
bindkey -M viins 'vv' vi-cmd-mode

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git git-flow svn python pip screen vi-mode vundle virtualenvwrapper mhalder macports osx)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
bindkey '^[[5~' history-beginning-search-backward  ## Page Up
bindkey '^[[6~' history-beginning-search-forward   ## Page Down

zstyle ':completion:*' special-dirs true

TERM=xterm-256color
